---

- name: Template warewulf.conf
  ansible.builtin.template:
        src: warewulf.conf.j2
        dest: "{{ ww4_config_prefix }}/etc/warewulf/warewulf.conf"
  tags: ['configure']

- name: Modify wwinit overlay to include the contents of /etc/fstab from the container
  ansible.builtin.blockinfile:
    path: "{{ ww4_warewulf4_path }}/overlays/wwinit/etc/fstab.ww"
    block: |
      # Begining of container /etc/fstab contents
      {{ '{{IncludeFrom $.Container "/etc/fstab"}}' }}
      # End of container /etc/fstab contents
    marker: "# {mark} ANSIBLE MANAGED BLOCK (wwinit overlay)"

- name: configure ww4 subsystems one by one with wwctl configure item
  ansible.builtin.command:
    cmd: "wwctl configure {{ item }}"
  loop:
    - dhcp
    - hostfile
    - nfs
    - ssh
    - tftp
  tags: ['configure','notest']

- name: start and enable warewulfd with systemd
  ansible.builtin.systemd:
    state:   restarted
    enabled: true
    name:    warewulfd
  tags: ['configure','notest']
