---
# tasks file for ansible_role_warewulf4

- ansible.builtin.include_role:
    name: ansible_role_epel

- name: Install Development tools and other dependencies
  ansible.builtin.dnf:
        name: ['@Development tools', "gpgme-devel", "firewalld"]
        state: present

- name: "Install servers & golang"
  ansible.builtin.dnf:
        name: ["golang","tftp-server","dhcp-server","nfs-utils"]
        state: present

- name: "checkout ww4 from github"
  ansible.builtin.git:
        repo: 'https://github.com/hpcng/warewulf.git'
        dest: "{{ ww4_git_path }}"
        version: "{{ ww4_git_version }}"

- name: Compile ww4
  make:
        chdir: "{{ ww4_git_path }}"
        target: "all"

- name: install ww4
  make:
        chdir: "{{ ww4_git_path }}"
        target: "install"
# Installed by default to /usr/local/bin/


- name: restart firewalld
  ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: firewalld

- name: add to firewall warefulf
  ansible.posix.firewalld:
        service: warewulf
        permanent: true
        state: enabled

- name: add to firewall nfs
  ansible.posix.firewalld:
        service: nfs
        permanent: true
        state: enabled

- name: add to firewall tftp
  ansible.posix.firewalld:
        service: tftp
        permanent: true
        state: enabled

# Should be "firewall-cmd --reload"
- name: restart firewalld again
  ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: firewalld


- name: Template warewulf.conf
  ansible.builtin.template:
        src: warewulf.conf.j2
        dest: /usr/local/etc/warewulf/warewulf.conf
