---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi9/ubi-init
    #image: rockylinux/rockylinux:latest
    pre_build_image: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
